<?php
if(!defined('XYHCMS_INSTALL')) exit('Access Denied');
$lang = array(
	'install_title' => 'XYHCMS 1.6安装向导',
	'install_license' => '行云海内容管理系统-安装用户协议',
	'install_is_lock' => '您已成功安装XYHCMS，需重新安装请手动删除网站目录下install/install.lock文件', 
	'install_db_error' => '数据库文件无法读取，请检查install/inc/xyhcms.sql是否存在。',	
	'agree_and_accept' => '同意并接受',	
	'detection_environment' => '检测环境',
	'data_create' => '创建数据',
	'complete_installation' => '完成升级',
	'environmental_testing' => '环境检测',
	'recommended_configuration' => '推荐配置',
	'current_status' => '当前状态',
	'operating_system' => '操作系统',
	'version' => '版本',
	'attachment_upload' => '附件上传',
	'extension' => '扩展',
	'directory_permissions' => '目录权限检测',
	'write' => '写入',
	'read' => '读取',
	'previous' => '上一步',
	'next' => '下一步',
	'database_information' => '数据库信息',
	'database_information_tip' => '安装后,原数据库会被清空,请做好备份',

	'install_mysql_host' => '数据库服务器',
	'install_mysql_host_intro' => '本地填写：localhost或127.0.0.1',
	'install_mysql_port' => '数据库端口',
	'install_mysql_port_intro' => '数据库端口一般为3306',

	'install_mysql_username' => '数据库用户名',
	'install_mysql_password' => '数据库密码',
	'install_mysql_name' => '数据库名称',
	'install_mysql_name_intro' => '不存在则自动创建',
	'install_mysql_prefix' => '数据库表前缀',
	'install_mysql_prefix_intro' => '推荐使用默认',
	'site_configuration' => '网站配置',
	'site_name' => '网站名称',
	'site_name_default' => '我的网站',
	'site_url' => '网站网址',
	'site_url_intro' => '请以http://或https://开头',
	'site_style' => '网站风格',
	'site_style_c' => '企业站',
	'site_style_b' => '博客站',
	'website_administrator' => '网站超级管理员',
	'username' => '用户名',
	'password' => '密　码',
	'password_intro' => '最少6位',
	'test_data' => '测试数据',
	'test_data_intro' => '添加默认数据！(适合新手第一次使用)',
	'Installation' => '安装中',
	'Data_initialization' => '数据初始化中',

	'installation_failed' => '安装失败',
	'installation_complete' => '安装完成',
	'installation_successful' => '安装成功',
	'installation_failed_reinstall' => '安装失败,请重新升级安装',
	'congratulations_installation_success' => '恭喜您，安装成功！',
	'please_delete_folder' => '请手动删除Update文件夹',	
	'visit_home' => '访问网站首页',
	'enter_admin' => '进入后台管理',

	'safe_notes' => '为了您站点的安全，安装完成后请立即删除网站根目录下的“Install”文件夹删除。',




	'php_extention_unload_gd' => '您的服务器没有安装这个PHP扩展：gd',
	'php_extention_unload_mbstring' => '您的服务器没有安装这个PHP扩展：mbstring',
	'php_extention_unload_mysql' => '您的服务器没有安装这个PHP扩展：mysql',
	'php_extention_unload_curl' => '您的服务器没有安装这个PHP扩展：curl',
	'mysql' => 'MySQL数据库',
	'mysql_unsupport' => '您的服务器不支持MYSQL数据库，无法安装XYHCMS。',
	'dirmod' => '目录和文件属性',
	'install_setting' => '数据库设置',
        'install_mysql_name_intro' => '同名数据库将被覆盖，请做好备份',
	'install_mysql_prefix' => '数据表前缀',
	'install_mysql_prefix_intro' => '同一数据库安装多XYHCMS程序时可改变默认值',
	'founder' => '管理员帐号设置',
	'install_founder_name' => '超级管理员帐号',
	'install_founder_password' => '管理员密码',
	'install_founder_rpassword' => '确认密码',
	
	'install_mysql_host_empty' => '数据库服务器不能为空',
	'install_mysql_username_empty' => '数据库帐号不能为空',
	'install_mysql_name_empty' => '数据库名称不能为空',
	'install_founder_name_empty' => '创建管理员帐号不能为空',
	'install_founder_password_length' => '管理员密码必须大于6位',
	
	'mysql_invalid_configure' => '数据库配置信息不完整',
	'mysql_invalid_prefix' => '您指定的数据表前缀包含点字符(".")，请返回修改。',
	'forbidden_character' => '用户名包含非法字符',
	'founder_invalid_email' => '电子邮件格式不正确',
	'founder_invalid_configure' => '创建者信息不完整',
	'founder_invalid_password' => '密码长度必须大于或等于6位',
	'config_log_success' => '数据库配置信息写入完成',
	'config_read_failed' => '数据库配置文件写入错误，请检查config.ini.php文件是否存在或属性是否为777',
	'yycms_rebuild' => '数据库中已经安装过 XYHCMS，继续安装会清空原有数据！',
	'mysql_import_data' => '点击下一步开始导入数据',
	'import_processing' => '导入数据库',
	'import_processing_error' => '导入数据库失败',
	'create_table' => '创建表',
	'create_founder' => '创建超级管理员帐号',
	'create_founder_success' => '超级管理员帐号创建成功',
	'create_founder_error' => '超级管理员帐号创建失败',
	'install_success' => '安装成功',
	'install_failure' => '安装失败',
	'reinstall' => '<a href="index.php">请点击这里重新安装</a>',
	'install_success_intro' => '安装程序执行完毕，请尽快删除整个 install 目录，以免被他人恶意利用。如安装成功后访问异常，请手动删除Admin/Runtime和Apps/Runtime目录下所有文件。如要重新安装，请删除install目录中的 install.lock 文件！',
	'install_dbFile_error' => '数据库文件无法读取，请检查install/inc/yycms.sql是否存在。',
	
	'install_step_license' => '1.许可协议',
	'install_step_os' => '2.环境检测',
	'install_step_option' => '3.安装配置',
	'install_step_finish' => '4.安装完成',
	
	'install_btn_start' => '开始安装',
	'install_btn_prev' => '上一步',
	'install_btn_next' => '下一步',
	'support' => '支持',
	'unsupport' => '不支持',
    'mustopen' => '必须开启',
	'suggestopen' => '建议开启',
);
?>